development:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27741
      options:
        server_selection_timeout: 1
  options:
    log_level: :warn


xdevelopment:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27741
      options:
        compressors: [zlib]
  options:
    log_level: :debug

