xdevelopment:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27100
  options:
    log_level: :debug


development:
  clients:
    default:
      database: mongoid
      hosts:
        - localhost:27741
      options:
        compressors: [zlib]
  options:
    log_level: :debug

