uri: mongodb://localhost:14440,localhost:14441
client_options:
  max_pool_size: 20
  socket_timeout: 3
  connect_timeout: 3
  server_selection_timeout: 3
application_timeout: 20
application_threads: 20
target_ops: 5
preexec:
  - sh: sudo iptables -D INPUT -p tcp --destination-port 14440 -j DROP || true
  - sh: sudo iptables -D INPUT -p tcp --destination-port 14441 -j DROP || true
exec:
  5:
    sh: sudo iptables -A INPUT -p tcp --destination-port 14440 -j DROP
  40:
    exit: true
