uri: mongodb://localhost:30200,localhost:30201,localhost:30202,localhost:30203,localhost:30204
client_options:
application_timeout: 20
application_threads: 20
# # of operations to perform per client/application thread per second
target_ops: 30
driver_log: /tmp/rs-restart-driver.log
client_log: /tmp/rs-restart-client.log
xpreexec:
  - sh: pgrep -f 30200 | grep -v $$ | xargs kill -9 2>/dev/null || true
  - sh: pgrep -f 30201 | grep -v $$ | xargs kill -9 2>/dev/null || true
  - sh: pgrep -f 30202 | grep -v $$ | xargs kill -9 2>/dev/null || true
  - sh: pgrep -f 30203 | grep -v $$ | xargs kill -9 2>/dev/null || true
  - sh: pgrep -f 30204 | grep -v $$ | xargs kill -9 2>/dev/null || true
  - sh: rm -rf /mnt/zram/sandbox/rs-restart
  - sh: mkdir -p /mnt/zram/sandbox/rs-restart
  - sh: "mlaunch --replicaset --name ruby-driver-rs --nodes 5 \
    --dir /mnt/zram/sandbox/rs-restart \
    --setParameter diagnosticDataCollectionEnabled=false \
    --wiredTigerCacheSizeGB 0.25 \
    --setParameter enableTestCommands=1 \
    --filePermissions 0666 \
    --binarypath /usr/local/m/versions/4.4 \
    --port 30200"
  - sh: "mongo --quiet --host ruby-driver-rs/localhost:30200,localhost:30201,localhost:30202 \
    --eval 'db.test.insertOne({foo:1})'"
  - sh: chmod -R go+rX /mnt/zram/sandbox/rs-restart
preexec:
  - sh: "mlaunch start --dir /mnt/zram/sandbox/rs-restart || true"
  - sh: chmod -R go+rX /mnt/zram/sandbox/rs-restart
exec:
  10:
    dbcmd:
      shutdown: 1
    allow_fail: true
  30:
    dbcmd:
      shutdown: 1
    allow_fail: true
  50:
    sh: "mlaunch start --dir /mnt/zram/sandbox/rs-restart"
  51:
    sh: chmod -R go+rX /mnt/zram/sandbox/rs-restart
  90:
    dbcmd:
      shutdown: 1
    allow_fail: true
  110:
    exit: true

server_log: /tmp/rs-restart-server.log
puma_workers: 4
puma_threads: 0:3
puma_port: 9001

client_stats: true
client_stats_interval: 5
client_stats_cluster_summary: false
