clusterType: REPLICASET
providerSettings:
  providerName: AWS
  instanceSizeName: M10
replicationSpecs:
  -
    numShards: 1
    regionsConfig:
      US_WEST_1:
        electableNodes: 3
        priority: 7
        readOnlyNodes: 0
